In [2]:
print('18BCB0108')
print('SAKSHAM DEWAN')

18BCB0108
SAKSHAM DEWAN


In [2]:
#1 Import the libraries

import numpy as np
import pandas as pd
import matplotlib as plt

In [3]:
#2 Read the training and test data into respective variables

train = pd.read_csv("trainT.csv")
test = pd.read_csv("testT.csv")



In [4]:
#3 Take a peak at the data
train.head(5)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [5]:
test.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [6]:
#4 Determine the variables

df = train[['Survived','Pclass','Sex','Age','Fare']] # double bracket: for attributes otherwise for values its single

#The attribute gender is categorical so encoding it into binary as no affect on the dataset

In [24]:
df = test[['Pclass','Sex','Age','Fare']]

In [25]:
#5 Encoding Gender values to 0 and 1
df['Sex']=df['Sex'].apply(lambda sex:1 if sex=="male" else 0)# for train

<ipython-input-25-1f61bc04fa01>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Sex']=df['Sex'].apply(lambda sex:1 if sex=="male" else 0)# for train


In [26]:
df['Sex']

0      1
1      0
2      1
3      1
4      0
      ..
413    1
414    0
415    1
416    1
417    1
Name: Sex, Length: 418, dtype: int64

In [27]:
df['Sex']=df['Sex'].apply(lambda sex:1 if sex=="male" else 0)# for test

<ipython-input-27-54b56e3f7dc4>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Sex']=df['Sex'].apply(lambda sex:1 if sex=="male" else 0)# for test


In [28]:
df['Sex']

0      0
1      0
2      0
3      0
4      0
      ..
413    0
414    0
415    0
416    0
417    0
Name: Sex, Length: 418, dtype: int64

In [9]:
df.isna().sum()

Survived      0
Pclass        0
Sex           0
Age         177
Fare          0
dtype: int64

In [10]:
#6 Handling Missing Values - Data Imputation

df["Age"] = df["Age"].fillna(df["Age"].median()) # median is robust to outliers

<ipython-input-10-55fa00cf087a>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Age"] = df["Age"].fillna(df["Age"].median()) # median is robust to outliers


In [11]:
df["Age"]

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ... 
886    27.0
887    19.0
888    28.0
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [12]:
#7 Set the Predictor and Response Variables
X = df.drop("Survived", axis = 1)
Y = df["Survived"]

In [13]:
X

Pclass  Sex   Age     Fare
0         3    1  22.0   7.2500
1         1    0  38.0  71.2833
2         3    0  26.0   7.9250
3         1    0  35.0  53.1000
4         3    1  35.0   8.0500
..      ...  ...   ...      ...
886       2    1  27.0  13.0000
887       1    0  19.0  30.0000
888       3    0  28.0  23.4500
889       1    1  26.0  30.0000
890       3    1  32.0   7.7500

[891 rows x 4 columns]

In [14]:
Y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [15]:
X.head()
Y.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
#8 Split the data into training and test sets

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.3, random_state = 25)

#Cross Validation - try this!

In [18]:
X_train

Pclass  Sex   Age      Fare
707       1    1  42.0   26.2875
246       3    0  25.0    7.7750
624       3    1  21.0   16.1000
96        1    1  71.0   34.6542
576       2    0  34.0   13.0000
..      ...  ...   ...       ...
317       2    1  54.0   14.0000
143       3    1  19.0    6.7500
474       3    0  22.0    9.8375
318       1    0  31.0  164.8667
132       3    0  47.0   14.5000

[623 rows x 4 columns]

In [19]:
#9 The logistic Regression Model
from sklearn.linear_model import LogisticRegression
logit = LogisticRegression()
logit.fit(X_train,Y_train)
logit.get_params()

{'C': 1.0,
 'class_weight': None,
 'dual': False,
 'fit_intercept': True,
 'intercept_scaling': 1,
 'l1_ratio': None,
 'max_iter': 100,
 'multi_class': 'auto',
 'n_jobs': None,
 'penalty': 'l2',
 'random_state': None,
 'solver': 'lbfgs',
 'tol': 0.0001,
 'verbose': 0,
 'warm_start': False}

In [20]:
#10 Y Predictions 
Y_pred = logit.predict(X_test)
Y_pred #y hat calculate the loss

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 0])

In [21]:
# Confusion Matrix
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(Y_test,Y_pred)
confusion_matrix

array([[136,  29],
       [ 31,  72]])

In [22]:
#12 Accuracy Score
from sklearn.metrics import accuracy_score
accuracy_score(Y_test,Y_pred)

0.7761194029850746

In [23]:
#13 Classification Report
from sklearn.metrics import classification_report
report = classification_report(Y_test,Y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.81      0.82      0.82       165
           1       0.71      0.70      0.71       103

    accuracy                           0.78       268
   macro avg       0.76      0.76      0.76       268
weighted avg       0.78      0.78      0.78       268



In [32]:
# explore one more classifier

from sklearn.tree import DecisionTreeRegressor  
regressor = DecisionTreeRegressor(random_state = 0)  
regressor.fit(X_train,Y_train) 

# repeat the test thing too

DecisionTreeRegressor(random_state=0)

In [33]:
regressor.get_params()

{'ccp_alpha': 0.0,
 'criterion': 'mse',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'presort': 'deprecated',
 'random_state': 0,
 'splitter': 'best'}

In [34]:
Y_pred = regressor.predict(X_test)
Y_pred #y hat calculate the loss

array([0.  , 0.  , 0.  , 1.  , 0.25, 0.5 , 0.  , 0.  , 1.  , 0.  , 1.  ,
       0.  , 0.  , 0.  , 0.5 , 1.  , 0.  , 1.  , 1.  , 1.  , 1.  , 1.  ,
       0.  , 0.  , 0.  , 0.  , 1.  , 1.  , 1.  , 1.  , 0.  , 1.  , 1.  ,
       1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 0.  , 1.  , 0.  , 1.  , 0.2 ,
       0.  , 1.  , 0.  , 1.  , 0.  , 0.  , 1.  , 1.  , 1.  , 0.  , 1.  ,
       0.  , 0.  , 0.  , 0.  , 0.  , 1.  , 0.  , 0.  , 0.  , 0.5 , 1.  ,
       1.  , 0.  , 0.  , 0.  , 0.  , 1.  , 1.  , 1.  , 0.2 , 0.25, 1.  ,
       0.2 , 1.  , 0.  , 0.  , 1.  , 0.  , 0.  , 0.  , 1.  , 0.  , 0.  ,
       0.  , 0.  , 0.  , 1.  , 0.  , 0.  , 0.  , 0.  , 0.  , 1.  , 0.  ,
       1.  , 0.  , 1.  , 1.  , 1.  , 1.  , 0.  , 1.  , 1.  , 0.  , 1.  ,
       1.  , 0.  , 1.  , 0.  , 1.  , 0.  , 1.  , 0.75, 1.  , 0.  , 0.  ,
       1.  , 0.  , 1.  , 1.  , 0.  , 0.  , 0.  , 0.  , 0.  , 1.  , 0.  ,
       1.  , 0.  , 1.  , 0.  , 0.  , 0.  , 0.  , 1.  , 0.  , 0.25, 0.  ,
       1.  , 0.  , 1.  , 1.  , 0.  , 0.2 , 0.  , 1.

In [1]:
print('18BCB0108')
print('SAKSHAM DEWAN')

18BCB0108
SAKSHAM DEWAN
